### ISSUE TITLE
Github comment broke

### ISSUE THREAD

**Issue by PatrickSUDO** [PatrickSUDO/PatrickSUDO.github.io#1]
cannot leave a comment

**Comment by sachsom95** [comment]
Pressing the comment section redirects to front page may be a broken link ?

**Comment by sachsom95** [comment]
The issue still persist gives error code 401 when I like user comment

**Comment by PatrickSUDO** [comment]
Sometimes the OAuth works but sometimes it doesn't, need further investigation

**Comment by PatrickSUDO** [comment]
Issue fixed by migrating to disqus
